mysite/mysite/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls()

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("all/", views.AllView.as_view(), name="all"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/frequency/", views.FrequencyView.as_view(), name="frequency"),
    path("statistics/", views.statistics, name="statistics"),
    path("add/", views.get_question, name="add"),
    path("account/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("courses/", views.CourseView.as_view(), name="courses"),
    path("course_register/", views.LearnerRegister, name="course_register"),
    path("add-course-question/", views.add_course_question, name="add_course_question"),
    path("<int:course_id>/course-vote/", views.course_vote, name="course_vote")
]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>{% block title %}Bienvenue sur mon site{% endblock %}</title>
</head>

<body>
    <header>
        <div class="header_container">
            {% block header %}{% endblock %}
                <div class="auth_div">
                    {% if user.is_authenticated %}
                        <span>Hi, {{ user.username }}</span>
                        <button>
                            <a href="{% url 'polls:logout' %}">Déconnexion</a>
                        </button>
                    {% else %}
                        <a href="{% url 'polls:login' %}">Connexion</a>
                    {% endif %}
                </div>
        </div>
    </header>

    <main id="content">
        {% block content %}{% endblock %}
    </main>
</body>
</html>