mysite/mysite/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + debug_toolbar_urls()

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("all/", views.AllView.as_view(), name="all"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/frequency/", views.FrequencyView.as_view(), name="frequency"),
    path("statistics/", views.statistics, name="statistics"),
    path("add/", views.get_question, name="add"),
    path("account/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("courses/", views.CourseView.as_view(), name="courses"),
    path("course_register/", views.LearnerRegister, name="course_register"),
    path("add-course-question/", views.add_course_question, name="add_course_question"),
    path("<int:course_id>/course-vote/", views.course_vote, name="course_vote")
]

mysite/polls/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import AbstractUser, User
from django.db.models import Sum
from django.utils import timezone

from django.db import models


MAX_LENGTH = 20


def text_excerpt(text, max_length):
    return text[:max_length] + ('...' if len(text) > max_length else '')


class Learner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.TextField()


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    hiring_date = models.DateTimeField("Hiring date")

    def __str__(self):
        return self.user.username


class Course(models.Model):
    teacher = models.ForeignKey(Teacher, related_name="courses", on_delete=models.CASCADE)
    learners = models.ManyToManyField(Learner, related_name="courses")
    name = models.CharField(max_length=100)
    start_date = models.DateTimeField("Starting date")
    end_date = models.DateTimeField("Ending date")

    def __str__(self):
        return self.name


class Question(models.Model):
    """Question entity"""
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def age(self):
        return timezone.now() - self.pub_date

    def get_choices(self):
        result = self.choice_set.aggregate(total=Sum('votes'))
        total = result['total']
        if total == 0:
            return [(c.choice_text, c.votes, 0) for c in self.choice_set.all()]

        return [(c.choice_text, c.votes, (c.votes / total)*100) for c in self.choice_set.all()]

    def get_max_choice(self):
        choices = self.choice_set.all()

        result = self.choice_set.aggregate(total=Sum('votes'))
        total = result['total']
        max_choice = max(choices, key=lambda c: c.votes / total)
        return max_choice.choice_text, max_choice.votes / total

    def __str__(self):
        return f"{self.pub_date} - {text_excerpt(self.question_text, MAX_LENGTH)}"

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        """
        Determinate if the question was published recently
        :return: boolean
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    """Choice of question"""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return text_excerpt(self.choice_text, MAX_LENGTH)

mysite/polls/views.py
from email.policy import default

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Avg, Max
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import generic

from .form import PollForm, LearnerRegisterForm, CourseQuestionForm
from .models import Question, Choice, Course, Learner


class IndexView(generic.TemplateView):
    template_name = "polls/index.html"


class AllView(generic.ListView):
    template_name = "polls/all.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


class FrequencyView(generic.DetailView):
    model = Question
    template_name = "polls/frequency.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["has_choices"] = self.object.get_choices()
        return context


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("polls:index")
    template_name = "authenticate/register.html"


class CourseView(LoginRequiredMixin, generic.ListView):
    login_url = "/polls/course_register/"
    template_name = "courses/courses.html"
    context_object_name = "latest_course_list"

    def get_queryset(self):
        return Course.objects.filter(start_date__lte=timezone.now()).order_by("start_date")[:10]

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        learner = Learner.objects.filter(user=self.request.user).first()

        if learner:
            taken_courses = learner.courses.all()
        else:
            taken_courses = []

        context["taken_courses"] = taken_courses
        return context


def vote(request, question_id):
    """
    Question votes
    :param request: request send
    :param question_id: id of the question
    :return: redirect to results view
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def statistics(request):
    total_questions = Question.objects.count()
    total_choices = Choice.objects.count()
    total_votes = Choice.objects.aggregate(Sum("votes"))
    avg_votes = Choice.objects.aggregate(Avg("votes", default=0))
    last_id = Question.objects.aggregate(id=Max("id"))
    last_question_recorded = Question.objects.get(pk=last_id.get("id"))

    context = {
        "total_questions": total_questions,
        "total_choices": total_choices,
        "total_votes": total_votes,
        "avg_votes": avg_votes,
        "last_question_recorded": last_question_recorded
    }

    return render(request, "polls/statistics.html", context)


def get_question(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:login"))

    if not hasattr(request.user, "teacher"):
        return HttpResponseForbidden("Vous n'avez pas la permission d'accéder à cette page.")

    if request.method == "POST":
        form = PollForm(request.POST)

        if form.is_valid():
            question_text = form.cleaned_data["question_text"]
            choice_texts = request.POST.getlist("choice_text[]")

            new_question = Question(question_text=question_text, pub_date=timezone.now())
            new_question.save()
            for choice_text in choice_texts:
                if choice_text.strip():
                    new_question.choice_set.create(question=new_question, choice_text=choice_text, votes=0)

            return HttpResponseRedirect(reverse("polls:all"))

    else:
        form = PollForm()

    return render(request, "polls/poll_form.html", {"form": form})


def log_in(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("polls:index"))
            else:
                return render(request, "authenticate/login.html", {"error_message": "You didn't enter a valid username or password"})

    return render(request, "authenticate/login.html")


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("polls:index"))


def LearnerRegister(request):
    if request.method == "POST":
        form = LearnerRegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            address = form.cleaned_data["address"]
            course = form.cleaned_data["course"]

            learner = Learner.objects.create(user=user, address=address)

            if course:
                learner.courses.set(course)

            login(request, user)
            return HttpResponseRedirect(reverse("polls:courses"))
    else:
        form = LearnerRegisterForm()

    return render(request, "courses/course_register.html", {"form": form})


def add_course_question(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:login"))

    if not hasattr(request.user, "teacher"):
        return HttpResponseForbidden("Vous n'avez pas la permission d'accéder à cette page.")

    if request.method == "POST":
        form = CourseQuestionForm(request.POST)

        if form.is_valid():
            course = form.cleaned_data["course"]
            question_text = form.cleaned_data["question_text"]
            choice_texts = request.POST.getlist("choice_text[]")

            new_question = Question(course=course, question_text=question_text, pub_date=timezone.now())
            new_question.save()
            for choice_text in choice_texts:
                if choice_text.strip():
                    new_question.choice_set.create(question=new_question, choice_text=choice_text, votes=0)

            return HttpResponseRedirect(reverse("polls:courses"))

    else:
        form = CourseQuestionForm()

    return render(request, "courses/add_course_question.html", {"form": form})


def course_vote(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    question = Question.objects.filter(course=course).first()
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

mysite/polls/templates/courses/add_course_question.html
{% extends "base.html" %}

{% block title %}Ajout d'une question{% endblock %}

{% block header %}<h1>Ajout d'un sondage du cours :</h1>{% endblock %}

{% block content %}
<div class="form_container">
    <form action="{% url 'polls:add_course_question' %}" method="post">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.question_text.errors }}
            {{ form.question_text.label_tag }}
            {{ form.question_text }}
        </div>
        <div class="fieldWrapper">
            <label for="choice1">Choix 1:</label>
            <input type="text" name="choice_text[]" id="choice1">
        </div>
        <div class="fieldWrapper">
            <label for="choice2">Choix 2:</label>
            <input type="text" name="choice_text[]" id="choice2">
        </div>
        <div class="fieldWrapper">
            <label for="choice3">Choix 3:</label>
            <input type="text" name="choice_text[]" id="choice3">
        </div>
        <div class="fieldWrapper">
            <label for="choice4">Choix 4:</label>
            <input type="text" name="choice_text[]" id="choice4">
        </div>
        <div class="fieldWrapper">
            <label for="choice4">Choix 5:</label>
            <input type="text" name="choice_text[]" id="choice5">
        </div>
        <div>
            <label>Cours</label>
            {{ form.course }}
        </div>
        <div class="form_button_div">
           <input type="submit" value="Add" class="form_button">
        </div>
    </form>
</div>
{% endblock %}

mysite/polls/templates/courses/course_register.html
{% extends 'base.html' %}

{% block title %}Inscription{% endblock %}

{% block content %}
<h2>S'enregistrer</h2>

<form action="{% url 'polls:course_register' %}" method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
        <label>Nom d'utilisateur :</label>
        {{ form.username }}
    </div>
    <div class="fieldWrapper">
        <label >Mot de passe :</label>
        {{ form.password1 }}
    </div>
    <div class="fieldWrapper">
        <label>Confirmer le mot de passe :</label>
        {{ form.password2 }}
    </div>
    <div class="fieldWrapper">
        <label>Adresse :</label>
        {{ form.address }}
    </div>
    <div class="fieldWrapper">
        <label>Cours :</label>
        {{ form.course }}
    </div>
    <button type="submit">S'incrire</button>
</form>
{% endblock %}

mysite/polls/templates/courses/courses.html
{% extends "base.html" %}

{% block title %}Cours{% endblock %}

{% block header %}<h1>Liste des cours disponibles</h1>{% endblock %}

{% block content %}
<div class="course_list">
    {% if latest_course_list %}
        <table>
            <thead>
                <tr>
                    <th>N°</th>
                    <th>Nom</th>
                    <th>Enseignant</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Inscrit</th>
                </tr>
            </thead>
            <tbody>
                {% for course in latest_course_list %}
                    <tr>
                        <td>{{ course.id }}</td>
                        <td>
                            <a href="{% url 'polls:course_vote' course.id %}">{{ course.name }}</a>
                        </td>
                        <td>{{ course.teacher.user.username }}</td>
                        <td>{{ course.start_date }}</td>
                        <td>{{ course.end_date }}</td>
                        {% if course in taken_courses %}
                        <td>Oui</td>
                        {% else %}
                        <td>Non</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% if request.user.teacher %}
    <a href="{% url 'polls:add_course_question' %}">Ajouter un sondage à un cours</a>
    {% endif %}
    <a href="{% url 'polls:course_register' %}">S'inscrire à un cours</a>
</div>
{% endblock %}